title: Place Folding Marks
description: Documentation of the QGIS plugin Place Folding Marks
theme: jekyll-theme-time-machine
show_downloads: true
github:
  repository_url: https://github.com/sanderhartveld/placefoldingmarks
  tar_url: false
  zip_url: https://github.com/sanderhartveld/placefoldingmarks/releases/download/v1.1/PlaceFoldingMarks.zip
