title: Place Folding Marks
description: Documentatie van de QGIS plugin Place Folding Marks
theme: jekyll-theme-time-machine
show_downloads: true
github:
  zip_url: https://github.com/sanderhartveld/placefoldingmarks/releases/download/v1.1/PlaceFoldingMarks.zip
